Repository FosolSolutions/coevent, pull requests merged in 2021-12, with the labels that each got.

#2 Setup fixes
  Makefile
  db/mssql/Dockerfile
  db/mssql/entrypoint.sh
  db/mssql/setup.sh
Labels: bug

#3 Fix setup scripts
  Makefile
  scripts/gen-env.sh
Labels: bug

#4 Add make nuke
  .gitignore
  Makefile
  scripts/gen-env.sh
  scripts/nuke.sh
  scripts/variables.sh
Labels: bug, enhancement

#5 Add GridTable component
  Makefile
  api/Makefile
  api/libs/Dockerfile.dal
  api/libs/dal/Migrations/Seed/Initial/01-Users.sql
  api/libs/dal/Migrations/Seed/Initial/02-Account.sql
  api/test/Coevent.Test.csproj
  app/.devcontainer/devcontainer.json
  app/package.json
  app/src/components/assets/coEventIconBl.svg
  app/src/components/assets/coEventIconWh.svg
  app/src/components/assets/coEventLogoBl.svg
  app/src/components/assets/coEventLogoWh.svg
  app/src/components/grid-table/GridTable.tsx
  app/src/components/grid-table/index.ts
  app/src/components/grid-table/styled/GridTableStyled.tsx
  app/src/components/grid-table/styled/index.ts
  app/src/components/index.ts
  app/src/components/menu/HomeMenu.tsx
  app/src/components/menu/MenuLink.tsx
  app/src/components/router/AppRouter.tsx
  app/src/components/router/PrivateRoute.tsx
  app/src/components/user-menu/UserMenu.tsx
  app/src/css/_colors.scss
  app/src/css/_variables.module.scss
  app/src/features/admin/account/Account.tsx
  app/src/features/admin/account/Accounts.tsx
  app/src/features/admin/account/accountColumns.tsx
  app/src/features/admin/account/index.ts
  app/src/features/admin/account/styled/GridStyled.tsx
  app/src/features/admin/account/styled/index.ts
  app/src/features/login/Login.tsx
  app/src/hooks/api/useAccounts.ts
  app/src/hooks/api/useAuth.ts
  app/src/hooks/padlock/PadlockContext.tsx
  app/src/hooks/padlock/interfaces/IPadlockHook.ts
  app/src/hooks/padlock/usePadlock.tsx
  app/src/hooks/summon/useSummon.tsx
  app/src/hooks/useIntersection.ts
  app/src/hooks/useIntersectionObserver.ts
  app/src/hooks/useNavState.ts
  app/yarn.lock
  auth/.gitignore
  auth/README.md
  auth/keycloak/Dockerfile
  auth/keycloak/README.md
  auth/keycloak/config/realm-export.json
  docker-compose.yml
  scripts/db-update.sh
  scripts/gen-env.sh
Labels: enhancement

#7 Minor Updates to Account
  app/src/App.tsx
  app/src/hooks/padlock/PadlockContext.tsx
  app/src/hooks/padlock/interfaces/IPadlockProps.ts
  app/src/hooks/padlock/interfaces/IPadlockProviderProps.ts
  app/src/hooks/padlock/interfaces/index.ts
  app/src/hooks/summon/SummonContext.tsx
  app/src/hooks/summon/interfaces/ISummonProviderProps.ts
  app/yarn.lock
  test/Coevent.postman_collection.json
Labels: enhancement
